# Generated by Django 6.1 on 2026-08-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_category_leadstatus_processstep_space_style_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de bloques. El orden del array es el orden en la página. Tipos: galeria, linea_de_tiempo, lista, metricas, parrafo, subsecciones, testimonio, video. Las fotos se suben abajo y en el bloque "galeria" se referencian por su id.'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de bloques. El orden del array es el orden en la página. Tipos: galeria, linea_de_tiempo, lista, metricas, parrafo, subsecciones, testimonio, video. Las fotos se suben abajo y en el bloque "galeria" se referencian por su id.'),
        ),
    ]
