# Generated by Django 6.1 on 2026-08-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_post_content_blocks_project_content_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('image', models.ImageField(upload_to='content/%Y/%m/')),
                ('alt', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad y SEO.', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
