# Generated by Django 6.0.5 on 2026-08-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de bloques. El orden del array es el orden en la página. Tipos: cierre, ejemplos, galeria, linea_de_tiempo, lista, metricas, parrafo, subsecciones, testimonio, video. Las fotos se suben abajo y en el bloque "galeria" se referencian por su id.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de bloques. El orden del array es el orden en la página. Tipos: cierre, ejemplos, galeria, linea_de_tiempo, lista, metricas, parrafo, subsecciones, testimonio, video. Las fotos se suben abajo y en el bloque "galeria" se referencian por su id.'),
        ),
    ]
